# Generated by Django 3.2.9 on 2021-11-17 16:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان ')),
                ('keywords', models.CharField(max_length=250, verbose_name='کلمه کلیدی ')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات ')),
                ('company_name', models.CharField(max_length=50, verbose_name='نام شرکت ')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='آدرس ')),
                ('phone', models.IntegerField(verbose_name='تلفن ثابت ')),
                ('mobile', models.IntegerField(verbose_name='موبایل ')),
                ('email', models.CharField(max_length=150, verbose_name='ایمیل ')),
                ('smpt_server', models.CharField(blank=True, max_length=50, verbose_name='smtp سرور ')),
                ('smtp_email', models.CharField(blank=True, max_length=50, verbose_name='smtp ایمیل')),
                ('smtp_password', models.CharField(blank=True, max_length=10, verbose_name='smtp پسورد')),
                ('smtp_port', models.CharField(blank=True, max_length=5, verbose_name='smtp پورت')),
                ('icon', models.ImageField(blank=True, upload_to='images/', verbose_name='آیکون/لوگو')),
                ('instagram', models.CharField(max_length=50, verbose_name='نام حساب در ایسنتاگرام ')),
                ('youtube', models.CharField(max_length=50, verbose_name='نام کانال در یوتیوب ')),
                ('twitter', models.CharField(max_length=50, verbose_name='نام صفحه در توییتر ')),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره ی ما')),
                ('contact_us', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='تماس با ما ')),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='منابع ')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=10, verbose_name='وضعیت ')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آپدیت خودکار')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات کلی',
            },
        ),
    ]
