# Generated by Django 3.2.9 on 2021-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام')),
                ('email', models.CharField(max_length=60, verbose_name='ایمیل')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='موضوع')),
                ('message', models.TextField(blank=True, max_length=255, verbose_name='پیام شما')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('خوانده شده', 'خوانده شده'), ('بسته', 'بسته')], default='جدید', max_length=10, verbose_name='وضعیت پیام')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی کاربر')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'بخش تماس با ما',
            },
        ),
    ]
