# Generated by Django 3.2.9 on 2021-11-17 15:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('keyword', models.CharField(max_length=255, verbose_name='کلمه کلیدی')),
                ('description', models.TextField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=10, verbose_name='وضعیت')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اسلاگ')),
                ('creat_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='eshop_product.category', verbose_name='سربخش کلی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان ')),
                ('keyword', models.CharField(max_length=255, verbose_name='کلمه کلیدی ')),
                ('description', models.TextField(max_length=255, verbose_name='توضیح کوتاه ')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر محصول ')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='قیمت محصول ')),
                ('amount', models.IntegerField(default=0, verbose_name='تعداد موجودی محصول ')),
                ('min_amount', models.IntegerField(default=1, verbose_name='حداقل موجودی محصول ')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس اسلاگ ')),
                ('details', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات محصول ')),
                ('status', models.CharField(choices=[('فعال', 'فعال'), ('غیر فعال', 'غیر فعال')], max_length=10, verbose_name='وضعیت محصول ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.category', verbose_name='زیر مجموعه ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name=' محصول ')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
    ]
