# Generated by Django 3.2.9 on 2021-11-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0003_alter_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='نظر کاربر'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=1, verbose_name='رتبه کاربر'),
        ),
    ]
