# Generated by Django 3.2.9 on 2021-11-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_home_Slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home_slider',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر اسلایدر'},
        ),
    ]
