# Generated by Django 3.2.9 on 2021-11-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_product', '0004_auto_20211123_2135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, verbose_name='کد رهگیری محصول ')),
                ('first_name', models.CharField(max_length=10, verbose_name='نام ')),
                ('last_name', models.CharField(max_length=10, verbose_name=' نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='همراه ')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='آدرس ')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name=' شهر ')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name=' کشور ')),
                ('total', models.FloatField(verbose_name='مجموعه خرید')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('انجام شده', 'انجام شده'), ('در حال آماده سازی', 'در حال آماده سازی'), ('در حال ارسال', 'در حال ارسال'), ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'), ('کنسل شده', 'کنسل شده')], default='New', max_length=25, verbose_name='وضعیت محصول ')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='شناسه آی پی ')),
                ('adminnote', models.CharField(blank=True, max_length=100, verbose_name='یاداشت مدیر ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'بخش سفارش',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد ')),
                ('price', models.FloatField(verbose_name='قیمت ')),
                ('amount', models.FloatField(verbose_name='مقدار محصول')),
                ('status', models.CharField(choices=[('جدید', 'جدید'), ('انجام شده', 'انجام شده'), ('کنسل شده', 'کنسل شده')], default='New', max_length=20, verbose_name='وضعیت سفارش محصول ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_Order.order', verbose_name='سفارش مربوط ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop_product.product', verbose_name='محصول سفارش داده شده ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش دهنده ')),
            ],
            options={
                'verbose_name': 'سفارش محصول',
                'verbose_name_plural': 'بخش سفارش محصول',
            },
        ),
    ]
