# Generated by Django 3.2.9 on 2021-11-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_Order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'سبد', 'verbose_name_plural': '  بخش سبد خرید'},
        ),
    ]
